### ISSUE TITLE
Publishing new release

### ISSUE THREAD

**Issue by scls19fr** [johnmyleswhite/BloomFilters.jl#28]
Following https://github.com/johnmyleswhite/BloomFilters.jl/pull/24#issuecomment-510549399

publishing a new release is necessary

**Comment by scls19fr** [comment]
https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677/157 should provide good guidance for transitioning from METADATA.jl registred project to the new Registration [JuliaRegistries/ General](https://github.com/JuliaRegistries/General)

**Comment by boydgreenfield** [comment]
... that was more complex than I would have liked (but thanks very much for the pointer @scls19fr!), but here's the PR on JuliaRegistries: https://github.com/JuliaRegistries/General/pull/1960. I've also tagged the current commit on master as `0.3.0`.
